#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

SOURCE_FILE="$SOURCECODE_WORK_DIR/nginx.conf"
TARGET_FILE="$DOKKU_ROOT/$APP/nginx.conf.d/app.custom.conf"

# Remove previously created custom file
test -f "$TARGET_FILE" && rm "$TARGET_FILE" 2>/dev/null

# Creates new custom file
test -f "$SOURCE_FILE" && cp "$SOURCE_FILE" "$TARGET_FILE" 2>/dev/null
