#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

SOURCE_FILE="$SOURCECODE_WORK_DIR/nginx.conf"
TARGET_FILE="$DOKKU_ROOT/$APP/nginx.conf.d/app.custom.conf"

if [[ -f "$TARGET_FILE"; ]] then
    rm "$TARGET_FILE" 2>/dev/null
fi

if [[ -f "$SOURCE_FILE"; ]] then
    cp "$SOURCE_FILE" "$TARGET_FILE" 2>/dev/null
fi