#!/usr/bin/env bash

set -eo pipefail
[[ $DOKKU_TRACE ]] && set -x

cmd-plugin-help() {
  declare desc="help command"
  declare CMD="$1"
  local plugin_name="custom-nginx-conf"
  local plugin_description="Applies custom nginx config"

  if [[ "$CMD" == "$plugin_name:help" ]]; then
    echo "$plugin_description"
  else
    cat <<help_desc
    $plugin_name, $plugin_description
help_desc
  fi
}
