#!/usr/bin/env bash

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_CORE_AVAILABLE_PATH/common/functions"

APP="$1"; verify_app_name "$APP"
TMP_WORK_DIR="$2"
TARGET_DIR="$DOKKU_ROOT/$APP/nginx.conf.d"

mkdir -p $TARGET_DIR

SOURCE_FILE="$TMP_WORK_DIR/custom-nginx.conf"
TARGET_FILE="$TARGET_DIR/app.custom.conf"

dokku_log_info2_quiet "Processing custom nginx"

# Remove previously created custom file
if [ -f "$TARGET_FILE" ]; then
    dokku_log_info1_quiet "Deleting previous custom nginx conf"
    rm "$TARGET_FILE" 2>/dev/null
else
    dokku_log_info1_quiet "No existing custom nginx conf"
fi

# Creates new custom file
if [ -f "$SOURCE_FILE" ]; then
    dokku_log_info1_quiet "Copying new custom nginx conf"
    cp "$SOURCE_FILE" "$TARGET_FILE" 2>/dev/null
else
    dokku_log_info1_quiet "No custom nginx conf in root directory"
fi
